# -*- coding: utf-8 -*-
"""Netflix Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9fiLySMvmIktXZE7zHVFfcWtArK2-TU

Import Libraries:
"""

import pandas as pd #data analysis & manupulation
import numpy as np # linear algebra
import matplotlib.pyplot as plt # data visuallize
import seaborn as sns # data visualize
import matplotlib.pyplot as plt
sns.set_style("whitegrid")
import warnings
warnings.filterwarnings("ignore")

"""Load Data files"""

df = pd.read_csv("/content/sample_data/netflix_titles.csv")
df["date_added"]=pd.to_datetime(df["date_added"].str.strip(), errors='coerce')
df.isnull().sum()
df.info()

"""Explore Data"""

print(df.columns)
df.describe()

"""Top 10 Countries"""

df_countries = df['country'].dropna().str.split(',').explode().str.strip()
top_10_countries = df_countries.value_counts().head(10)

"""Filter Top Countries & Split Genres"""

top_countries_list = top_10_countries.index.tolist()
df_top_countries = df[df['country'].notna()]
df_top_countries = df_top_countries.assign(country=df_top_countries['country'].str.split(',')).explode('country')
df_top_countries['country'] = df_top_countries['country'].str.strip()
df_top_countries = df_top_countries[df_top_countries['country'].isin(top_countries_list)]
# Spliting genres into rows
df_top_countries = df_top_countries.assign(genre=df_top_countries['listed_in'].str.split(',')).explode('genre')
df_top_countries['genre'] = df_top_countries['genre'].str.strip()



"""Count Movies and TV Shows"""

df["type"].value_counts()
df["country"].value_counts().head(10)
sns.countplot(x="type",data=df)
plt.title("Number of Movies and TV Shows on Netflix")
plt.show()

"""Titles Added Over Time"""

df["year_added"]=df["date_added"].dt.year.astype("Int64")
netflix_red="#E50914" #try to make the lines colour as red as netflix
plt.figure(figsize=(10,6))
order=sorted(df["year_added"].dropna().unique())
sns.countplot(x="year_added",data=df,order=order,color=netflix_red)
plt.title("Number of Titles Added to Netflix Over Time",color="black")
plt.xlabel("Year Added")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

"""Top 10 Countries Bar Chart"""

plt.figure(figsize=(10,6))
sns.barplot(x=top_10_countries.values, y=top_10_countries.index, palette="Reds_r")
plt.title("Top 10 Countries with Most Netflix Titles", fontsize=14, fontweight='bold')
plt.xlabel("Number of Titles")
plt.ylabel("Country")
plt.show()

"""Top 3 Genres Pie Charts in top ten Countries"""

plt.figure(figsize=(20,15))
for i, country in enumerate(top_countries_list):
    plt.subplot(4, 3, i+1)
    # Filter for this country
    df_country = df_top_countries[df_top_countries['country'] == country]
    # Get top 3 genres
    top_genres = df_country['genre'].value_counts().head(3)
    plt.pie(top_genres.values, labels=top_genres.index, autopct='%1.1f%%', startangle=140,colors=sns.color_palette("Reds_r", len(top_genres)))
    plt.title(f"Top 3 Genres in {country}", fontsize=12, pad=20)
    plt.axis('equal')
plt.tight_layout()
plt.show()